//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Input/InputManager.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputManager: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputManager()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputManager"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""185c9621-5f7c-4650-8527-2e9c5f76c67e"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""5e850a4a-4cae-4c43-aed0-7bc4dd488a98"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""5874ccf8-49d7-43eb-9e9c-d1921d95d650"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Walk"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f022f2db-a77d-4872-a2da-b8624cde2f14"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c6b8abb4-783a-47c1-bab5-b995705dda8a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Crouch"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0eca66cf-575d-4f54-82b5-79eca63f4c8b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""99fdd5a5-1968-414e-9047-943a0d616d27"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press(behavior=2)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleShootMode"",
                    ""type"": ""Button"",
                    ""id"": ""adde10d4-1037-4e8f-bcd7-03b8f5adfac8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use"",
                    ""type"": ""Button"",
                    ""id"": ""5a94c5fc-df13-4711-9a8e-c3d667a36e0d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleWeaponInventory"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4df7f42f-2a39-4736-9364-006397a777a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeaponOne"",
                    ""type"": ""Button"",
                    ""id"": ""22604003-bdd3-45e4-b562-e60094759bf0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeaponTwo"",
                    ""type"": ""Button"",
                    ""id"": ""f2a23b91-6dcf-401b-a192-7e61c396b74f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeaponThree"",
                    ""type"": ""Button"",
                    ""id"": ""9b8af3e5-0bce-4607-afbb-39633e1a3af7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeaponThree1"",
                    ""type"": ""Button"",
                    ""id"": ""268c98b0-8a3f-4a58-b5e8-89c29cdc9289"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SelectWeaponThree2"",
                    ""type"": ""Button"",
                    ""id"": ""8c6633b2-70d5-449c-84ca-b34cbd4f7f3b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TooglePauseMenu"",
                    ""type"": ""Button"",
                    ""id"": ""d14ade03-b3bd-46ce-bace-5603fb16c90d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleItemInventory"",
                    ""type"": ""Button"",
                    ""id"": ""30b04b97-0a7a-438e-928a-1c3158c2bf67"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ToggleUpgradeMenu"",
                    ""type"": ""Button"",
                    ""id"": ""a4f1f1ba-1720-4202-b601-39c4b8df983c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""785687db-93e4-441b-8d33-ad508689604f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""8c94feeb-6fd0-4466-aedb-0568ca784ab1"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""93bb896d-a534-4626-a6e9-d1a14e493059"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""9f019bb0-451d-4607-951f-d4760e3bf09f"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e5b93851-8fd3-4c5b-ac95-59daaa1a3dd8"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""f026d0cf-29b0-4ead-824d-623684ae74ae"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7e3b859-09b6-4352-b164-4977f4271e96"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Walk"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7ab5166-941b-41a7-bf9a-69f19af17a9a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0503cb45-021c-4c93-9d3d-b48e82b1c43b"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Crouch"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42124d62-2ca1-4331-9036-73f78d64123a"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c62f2f57-c2cc-458b-a575-2c16e4a2c1de"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleShootMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e94de1f4-0d94-457c-8a7e-91f2aaeca7e5"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e509953a-c750-4dd2-9652-8eca243d861f"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeaponOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fffd11a9-f92d-4043-9c1d-d7a5a36713cf"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeaponTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""44cdf869-05eb-4324-9f86-7570313cacce"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeaponThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9364e18d-aaa1-49c2-98db-9c299091e25a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleWeaponInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a4ceec8-a019-416d-8353-7ef70f9796fb"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TooglePauseMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9767ad43-000d-4742-b16b-7c77375176e2"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleItemInventory"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3f676fda-2cb0-47d6-a23b-5426ba7655d3"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ToggleUpgradeMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8aa59ca6-63f1-4932-bf38-ffd395628b8e"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeaponThree1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1084f24-388e-408f-a040-6dbcd1514a51"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SelectWeaponThree2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Move = m_Player.FindAction("Move", throwIfNotFound: true);
        m_Player_Look = m_Player.FindAction("Look", throwIfNotFound: true);
        m_Player_Walk = m_Player.FindAction("Walk", throwIfNotFound: true);
        m_Player_Jump = m_Player.FindAction("Jump", throwIfNotFound: true);
        m_Player_Crouch = m_Player.FindAction("Crouch", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_ToggleShootMode = m_Player.FindAction("ToggleShootMode", throwIfNotFound: true);
        m_Player_Use = m_Player.FindAction("Use", throwIfNotFound: true);
        m_Player_ToggleWeaponInventory = m_Player.FindAction("ToggleWeaponInventory", throwIfNotFound: true);
        m_Player_SelectWeaponOne = m_Player.FindAction("SelectWeaponOne", throwIfNotFound: true);
        m_Player_SelectWeaponTwo = m_Player.FindAction("SelectWeaponTwo", throwIfNotFound: true);
        m_Player_SelectWeaponThree = m_Player.FindAction("SelectWeaponThree", throwIfNotFound: true);
        m_Player_SelectWeaponThree1 = m_Player.FindAction("SelectWeaponThree1", throwIfNotFound: true);
        m_Player_SelectWeaponThree2 = m_Player.FindAction("SelectWeaponThree2", throwIfNotFound: true);
        m_Player_TooglePauseMenu = m_Player.FindAction("TooglePauseMenu", throwIfNotFound: true);
        m_Player_ToggleItemInventory = m_Player.FindAction("ToggleItemInventory", throwIfNotFound: true);
        m_Player_ToggleUpgradeMenu = m_Player.FindAction("ToggleUpgradeMenu", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_Move;
    private readonly InputAction m_Player_Look;
    private readonly InputAction m_Player_Walk;
    private readonly InputAction m_Player_Jump;
    private readonly InputAction m_Player_Crouch;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_ToggleShootMode;
    private readonly InputAction m_Player_Use;
    private readonly InputAction m_Player_ToggleWeaponInventory;
    private readonly InputAction m_Player_SelectWeaponOne;
    private readonly InputAction m_Player_SelectWeaponTwo;
    private readonly InputAction m_Player_SelectWeaponThree;
    private readonly InputAction m_Player_SelectWeaponThree1;
    private readonly InputAction m_Player_SelectWeaponThree2;
    private readonly InputAction m_Player_TooglePauseMenu;
    private readonly InputAction m_Player_ToggleItemInventory;
    private readonly InputAction m_Player_ToggleUpgradeMenu;
    public struct PlayerActions
    {
        private @InputManager m_Wrapper;
        public PlayerActions(@InputManager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_Player_Move;
        public InputAction @Look => m_Wrapper.m_Player_Look;
        public InputAction @Walk => m_Wrapper.m_Player_Walk;
        public InputAction @Jump => m_Wrapper.m_Player_Jump;
        public InputAction @Crouch => m_Wrapper.m_Player_Crouch;
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @ToggleShootMode => m_Wrapper.m_Player_ToggleShootMode;
        public InputAction @Use => m_Wrapper.m_Player_Use;
        public InputAction @ToggleWeaponInventory => m_Wrapper.m_Player_ToggleWeaponInventory;
        public InputAction @SelectWeaponOne => m_Wrapper.m_Player_SelectWeaponOne;
        public InputAction @SelectWeaponTwo => m_Wrapper.m_Player_SelectWeaponTwo;
        public InputAction @SelectWeaponThree => m_Wrapper.m_Player_SelectWeaponThree;
        public InputAction @SelectWeaponThree1 => m_Wrapper.m_Player_SelectWeaponThree1;
        public InputAction @SelectWeaponThree2 => m_Wrapper.m_Player_SelectWeaponThree2;
        public InputAction @TooglePauseMenu => m_Wrapper.m_Player_TooglePauseMenu;
        public InputAction @ToggleItemInventory => m_Wrapper.m_Player_ToggleItemInventory;
        public InputAction @ToggleUpgradeMenu => m_Wrapper.m_Player_ToggleUpgradeMenu;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
            @Walk.started += instance.OnWalk;
            @Walk.performed += instance.OnWalk;
            @Walk.canceled += instance.OnWalk;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @Crouch.started += instance.OnCrouch;
            @Crouch.performed += instance.OnCrouch;
            @Crouch.canceled += instance.OnCrouch;
            @Attack.started += instance.OnAttack;
            @Attack.performed += instance.OnAttack;
            @Attack.canceled += instance.OnAttack;
            @ToggleShootMode.started += instance.OnToggleShootMode;
            @ToggleShootMode.performed += instance.OnToggleShootMode;
            @ToggleShootMode.canceled += instance.OnToggleShootMode;
            @Use.started += instance.OnUse;
            @Use.performed += instance.OnUse;
            @Use.canceled += instance.OnUse;
            @ToggleWeaponInventory.started += instance.OnToggleWeaponInventory;
            @ToggleWeaponInventory.performed += instance.OnToggleWeaponInventory;
            @ToggleWeaponInventory.canceled += instance.OnToggleWeaponInventory;
            @SelectWeaponOne.started += instance.OnSelectWeaponOne;
            @SelectWeaponOne.performed += instance.OnSelectWeaponOne;
            @SelectWeaponOne.canceled += instance.OnSelectWeaponOne;
            @SelectWeaponTwo.started += instance.OnSelectWeaponTwo;
            @SelectWeaponTwo.performed += instance.OnSelectWeaponTwo;
            @SelectWeaponTwo.canceled += instance.OnSelectWeaponTwo;
            @SelectWeaponThree.started += instance.OnSelectWeaponThree;
            @SelectWeaponThree.performed += instance.OnSelectWeaponThree;
            @SelectWeaponThree.canceled += instance.OnSelectWeaponThree;
            @SelectWeaponThree1.started += instance.OnSelectWeaponThree1;
            @SelectWeaponThree1.performed += instance.OnSelectWeaponThree1;
            @SelectWeaponThree1.canceled += instance.OnSelectWeaponThree1;
            @SelectWeaponThree2.started += instance.OnSelectWeaponThree2;
            @SelectWeaponThree2.performed += instance.OnSelectWeaponThree2;
            @SelectWeaponThree2.canceled += instance.OnSelectWeaponThree2;
            @TooglePauseMenu.started += instance.OnTooglePauseMenu;
            @TooglePauseMenu.performed += instance.OnTooglePauseMenu;
            @TooglePauseMenu.canceled += instance.OnTooglePauseMenu;
            @ToggleItemInventory.started += instance.OnToggleItemInventory;
            @ToggleItemInventory.performed += instance.OnToggleItemInventory;
            @ToggleItemInventory.canceled += instance.OnToggleItemInventory;
            @ToggleUpgradeMenu.started += instance.OnToggleUpgradeMenu;
            @ToggleUpgradeMenu.performed += instance.OnToggleUpgradeMenu;
            @ToggleUpgradeMenu.canceled += instance.OnToggleUpgradeMenu;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
            @Walk.started -= instance.OnWalk;
            @Walk.performed -= instance.OnWalk;
            @Walk.canceled -= instance.OnWalk;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @Crouch.started -= instance.OnCrouch;
            @Crouch.performed -= instance.OnCrouch;
            @Crouch.canceled -= instance.OnCrouch;
            @Attack.started -= instance.OnAttack;
            @Attack.performed -= instance.OnAttack;
            @Attack.canceled -= instance.OnAttack;
            @ToggleShootMode.started -= instance.OnToggleShootMode;
            @ToggleShootMode.performed -= instance.OnToggleShootMode;
            @ToggleShootMode.canceled -= instance.OnToggleShootMode;
            @Use.started -= instance.OnUse;
            @Use.performed -= instance.OnUse;
            @Use.canceled -= instance.OnUse;
            @ToggleWeaponInventory.started -= instance.OnToggleWeaponInventory;
            @ToggleWeaponInventory.performed -= instance.OnToggleWeaponInventory;
            @ToggleWeaponInventory.canceled -= instance.OnToggleWeaponInventory;
            @SelectWeaponOne.started -= instance.OnSelectWeaponOne;
            @SelectWeaponOne.performed -= instance.OnSelectWeaponOne;
            @SelectWeaponOne.canceled -= instance.OnSelectWeaponOne;
            @SelectWeaponTwo.started -= instance.OnSelectWeaponTwo;
            @SelectWeaponTwo.performed -= instance.OnSelectWeaponTwo;
            @SelectWeaponTwo.canceled -= instance.OnSelectWeaponTwo;
            @SelectWeaponThree.started -= instance.OnSelectWeaponThree;
            @SelectWeaponThree.performed -= instance.OnSelectWeaponThree;
            @SelectWeaponThree.canceled -= instance.OnSelectWeaponThree;
            @SelectWeaponThree1.started -= instance.OnSelectWeaponThree1;
            @SelectWeaponThree1.performed -= instance.OnSelectWeaponThree1;
            @SelectWeaponThree1.canceled -= instance.OnSelectWeaponThree1;
            @SelectWeaponThree2.started -= instance.OnSelectWeaponThree2;
            @SelectWeaponThree2.performed -= instance.OnSelectWeaponThree2;
            @SelectWeaponThree2.canceled -= instance.OnSelectWeaponThree2;
            @TooglePauseMenu.started -= instance.OnTooglePauseMenu;
            @TooglePauseMenu.performed -= instance.OnTooglePauseMenu;
            @TooglePauseMenu.canceled -= instance.OnTooglePauseMenu;
            @ToggleItemInventory.started -= instance.OnToggleItemInventory;
            @ToggleItemInventory.performed -= instance.OnToggleItemInventory;
            @ToggleItemInventory.canceled -= instance.OnToggleItemInventory;
            @ToggleUpgradeMenu.started -= instance.OnToggleUpgradeMenu;
            @ToggleUpgradeMenu.performed -= instance.OnToggleUpgradeMenu;
            @ToggleUpgradeMenu.canceled -= instance.OnToggleUpgradeMenu;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnWalk(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnCrouch(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnToggleShootMode(InputAction.CallbackContext context);
        void OnUse(InputAction.CallbackContext context);
        void OnToggleWeaponInventory(InputAction.CallbackContext context);
        void OnSelectWeaponOne(InputAction.CallbackContext context);
        void OnSelectWeaponTwo(InputAction.CallbackContext context);
        void OnSelectWeaponThree(InputAction.CallbackContext context);
        void OnSelectWeaponThree1(InputAction.CallbackContext context);
        void OnSelectWeaponThree2(InputAction.CallbackContext context);
        void OnTooglePauseMenu(InputAction.CallbackContext context);
        void OnToggleItemInventory(InputAction.CallbackContext context);
        void OnToggleUpgradeMenu(InputAction.CallbackContext context);
    }
}
